name       : kitemmodels
version    : 5.51.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kitemmodels-5.51.0.tar.xz : 6e839e02169e505b8030f26977cf7146d2a03167ead98485beb5d42fd71ab009
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
