name       : kitemmodels
version    : 5.43.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kitemmodels-5.43.0.tar.xz : ad617dc843297c2c4d5db97ea528c44c886d52c89125a77f9494da09de8187fb
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
