name       : kitemmodels
version    : 5.38.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.38/kitemmodels-5.38.0.tar.xz : 4cfa7661b6d3c1e242b92c9200383400398af1db341dbbd2de573429898d4068
license    : LGPL-2.1
component  : programming
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
