name       : kitemmodels
version    : 5.41.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/kitemmodels-5.41.0.tar.xz : b39487f5e1f004ce42f021bc9108b717f99a08875c662dc15dd0ba88247b768e
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
