name       : kitemmodels
version    : 5.39.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.39/kitemmodels-5.39.0.tar.xz : 699a1e7e1c78159efb501afc197f9b9959a800405da1ed9de9115ea13c98c0ae
license    : LGPL-2.1
component  : programming
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
