name       : kitemmodels
version    : 5.77.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kitemmodels-5.77.0.tar.xz : decc3f607a0b2e9e6d585188eb6664a2cf06646db50d4d60dce83d96a0456534
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
