name       : kitemmodels
version    : 5.80.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kitemmodels-5.80.0.tar.xz : 93948d1b2a29a9d6e8c436af5bc0ac5fc59e0d7a5632a5c611ee31a648856faf
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
