name       : kitemmodels
version    : 5.45.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/kitemmodels-5.45.0.tar.xz : 81cf879c8ca546bb1626c3c3fcd82d365f0d5ee45aba5066be8b3b468ddeab22
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
