name       : kitemmodels
version    : 5.53.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kitemmodels-5.53.0.tar.xz : 747d2c4f9e78db802971172b31bb342fb4376b68092bad65f2ac99fadc297cbe
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
