name       : kitemmodels
version    : 5.54.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kitemmodels-5.54.0.tar.xz : c09c465e8a2494f4f772ea81dd6398d94074ab3e753101febb93aca5cbd97ce8
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
