name       : kitemmodels
version    : 5.74.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kitemmodels-5.74.0.tar.xz : 89c91051445137959e3dd7276d428adaff09b1ca9980f37d4a66d0c34c7b36c1
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
