name       : kitemmodels
version    : 5.67.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kitemmodels-5.67.0.tar.xz : aefdd85a83a6803b33793f46ca74c3e8048b2cc3f8c7d7c5b5f4e9fa370d6b08
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
