name       : kitemmodels
version    : 5.48.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kitemmodels-5.48.0.tar.xz : ee01915a9aeef0c7c077a195e5497aae9aa1ac7de60c8431549f3c4f3c76608d
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
