name       : kitemmodels
version    : 5.65.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kitemmodels-5.65.0.tar.xz : 01980a8b518cdb442ace10f7a61dacec1cb61ff708d86edf83ee079cb6451d41
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
