name       : kitemmodels
version    : 5.50.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kitemmodels-5.50.0.tar.xz : 66e0f32ed007a30712b74df06c457029037c499f4fc699f80735ffb822769eb0
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
