name       : kitemmodels
version    : 5.32.0
release    : 4
source     :
    - http://download.kde.org/stable/frameworks/5.32/kitemmodels-5.32.0.tar.xz : 71fe0a5c2ad9f0f89dfbc2e9ccbc2223b7fa2723166de6f510f8f6d8e469b453
license    : LGPL-2.1
component  : programming
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
