name       : kitemmodels
version    : 5.49.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kitemmodels-5.49.0.tar.xz : 4f368c88ad9254662c9ef0765394e659ac54c9003cf65c0bd1129012c05030bb
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
