name       : kitemmodels
version    : 5.40.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kitemmodels-5.40.0.tar.xz : a9bb04bde2b445fb23435619703aa38dd5ccb0f9fa2caaed1fe960061ec04546
license    : LGPL-2.1
component  : programming
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
