name       : kitemmodels
version    : 5.47.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kitemmodels-5.47.0.tar.xz : 7a0a76e5253389c1ed459249a05e463fed140b1adf20db1416da167d5c56a104
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
