name       : kitemmodels
version    : 5.28.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.28/kitemmodels-5.28.0.tar.xz : 1f1d7b014d60d1f52ee4c67a5c8eb8e5f0bf39df788b8c7475a7c9cab0e6277e
license    : LGPL-2.1
component  : programming
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
