name       : kitemmodels
version    : 5.63.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kitemmodels-5.63.0.tar.xz : 2d978b4403c2b88f3b1c2795260c4a491d2c6278cf0ac02814afbdb41a787081
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
