name       : kitemmodels
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/kitemmodels-5.35.0.tar.xz : 87db350ea675b7fdca5b6b14f56b12db51ecb08d981c08cfa196fb0d2b9a70a2
license    : LGPL-2.1
component  : programming
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
