name       : kitemmodels
version    : 5.56.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/kitemmodels-5.56.0.tar.xz : 2fcf1c08766096c9e62fd40087013e7fd69900d8e5d306d392817949e15ea18e
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
