name       : kitemmodels
version    : 5.25.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.25/kitemmodels-5.25.0.tar.xz : e44a5c4ba997993057e8ebda6df400c3f1b97bf81d11bb02af27950ff1cd749d
license    : LGPL-2.1
component  : programming
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
