name       : kitemmodels
version    : 5.36.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.36/kitemmodels-5.36.0.tar.xz : 2a05bc2f807b725de0515dbc12f031b00026e97d0901a8d05f475ad9b2926b23
license    : LGPL-2.1
component  : programming
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
