name       : kitemmodels
version    : 5.46.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/kitemmodels-5.46.0.tar.xz : 02734480c9893f02fe3d277267909a28d52648a5dac173c9987d5aac165ec877
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Set of item models extending the Qt model-view framework.
description: |
    Set of item models extending the Qt model-view framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
